# Generated by Django 5.2.15 on 2026-10-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuisine',
                'verbose_name_plural': 'Cuisines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('restaurant_type', models.CharField(choices=[('Veg', 'Pure Veg'), ('Non-Veg', 'Non-Veg'), ('Both', 'Both Veg & Non-Veg')], db_index=True, default='Both', max_length=10, verbose_name='Restaurant Type')),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, default='Bengaluru', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.2, max_digits=3)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True, verbose_name='Open / Accepting Orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuisines', models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.cuisine')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-rating', 'name'],
                'indexes': [models.Index(fields=['name'], name='restaurants_name_0080ba_idx'), models.Index(fields=['city'], name='restaurants_city_6db275_idx'), models.Index(fields=['restaurant_type'], name='restaurants_restaur_876c8a_idx')],
            },
        ),
    ]
