# Generated by Django 5.2.15 on 2026-06-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.URLField(blank=True, help_text='Provide a valid image URL', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.URLField(blank=True, help_text='Provide a valid image URL', max_length=1024, null=True),
        ),
    ]
