# Generated by Django 5.2.15 on 2026-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_fooditem_image_alter_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, help_text='Full address or area of the restaurant', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='veg_nonveg',
            field=models.CharField(choices=[('Veg', 'Pure Vegetarian'), ('Non-Veg', 'Non-Vegetarian'), ('Both', 'Veg & Non-Veg')], default='Both', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.URLField(blank=True, help_text='Paste a valid image URL (https://...)', max_length=1024, null=True),
        ),
    ]
