# Generated by Django 5.2.15 on 2026-10-09 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='🍽️', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Food Name')),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8, verbose_name='Price (₹)')),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], db_index=True, default='Veg', max_length=10, verbose_name='Type (Veg/Non-Veg)')),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_items', to='menu.category', verbose_name='Category')),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='restaurants.cuisine', verbose_name='Cuisine')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='menu_foodit_name_cc8ea9_idx'), models.Index(fields=['price'], name='menu_foodit_price_3e0fc4_idx'), models.Index(fields=['food_type'], name='menu_foodit_food_ty_123a83_idx'), models.Index(fields=['is_available'], name='menu_foodit_is_avai_f85550_idx'), models.Index(fields=['restaurant', 'is_available'], name='menu_foodit_restaur_fd9676_idx')],
            },
        ),
    ]
